---
- name: Run swapoff -a command to disable all swaps
  command: |
    swapoff -a

- name: remove swap from fstab
  lineinfile:
    path: '/etc/fstab'
    regexp: '\sswap\s'
    state: 'absent'

- name: Create kernel config file in  /etc/modules-load.d/k8s.conf
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: br_netfilter
    mode: 0655

- name: Create system config file in /etc/sysctl.d/k8s.conf
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    mode: 0644
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Add Kubernetes repo
  yum_repository:
    name: kubernetes
    file: kubernetes.repo
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
    repo_gpgcheck: yes
    exclude: kubelet kubeadm kubectl 

- name: Disable SELinux
  selinux:
    state: disabled


- name: Install kubelet, kubeadm, kubectl
  yum:
    name: "{{ packages }}"
    disable_excludes: kubernetes
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- name: Start service kubelet and enable it
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: yes

- name: Reboot host and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: reboot_after_done